[package]
name = "randr"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
uuid = { version = "1.4.1", features = ["v4"] }
clap = { version = "4.4.6", features = ["derive"] }
prettytable-rs = "0.10.0"
